default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_dev
  password: violin146
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: diaryapi_development

test:
  <<: *default
  database: diaryapi_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
