default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: rails_dev
  password: violin146
  host: localhost
  port: 5432
  database: diaryapi_development

test:
  <<: *default
  database: diaryapi_test

production:
  <<: *default
  database: diaryapi_production
